@host = http://localhost:3000/stream-quality-report
POST {{host}}/get-api-video
Content-Type: application/json

{
    "region": "CEBU",
    "streamType": "RTMP",
    "resolution": "720p",
    "channel": "BTCB02m",
    "timestamp": 1708312560009
}