@host =  http://localhost:3000/stream-quality-report
POST {{host}}/get-image-response
Content-Type: application/json

{
    "region": "CEBU",
    "streamType": "RTMP",
    "channel": "BTCB02",
    "timestamp": 1706523840005
}